Debug output, disable ring-balancing for now

diff --git a/hooks/swift-proxy-common b/hooks/swift-proxy-common
--- a/hooks/swift-proxy-common
+++ b/hooks/swift-proxy-common
@@ -82,10 +82,18 @@ function add_to_ring {
   # swift-ring-builder returns 1 for success, 2 for zero.
   # TODO: File bug for return codes
   echo "Updating $1 ring. Adding $3:$4, zone $2, device $5"
+  echo "swift-ring-builder /etc/swift/$1.builder add z$2-$3:$4/$5 100"
   swift-ring-builder /etc/swift/$1.builder add \
     z$2-$3:$4/$5 100
-  [[ $? == "1" ]] && return 0
-  return 1
+  rc=$?
+  echo $rc
+  if [[ $rc == "1" ]] ; then
+    echo "Added to ring: $3:$4, zone $2, device $5"
+    return 0
+  else
+    echo "Failed to add to ring."
+    return 1
+  fi
 }
 
 function rebalance_ring {
diff --git a/hooks/swift-proxy-relations b/hooks/swift-proxy-relations
--- a/hooks/swift-proxy-relations
+++ b/hooks/swift-proxy-relations
@@ -50,26 +50,33 @@ function proxy_changed {
   PORT=6000
   RINGS="object container account"
 
-  # reinitialize rings if there are any missing
-  ring_missing=0
   for i in $RINGS ; do
-    [[ ! -e /etc/swift/$i.builder ]] && ring_missing=1
+    if [[ ! -e /etc/swift/$i.builder ]] ; then
+      echo "Ring $i missing, initializing"
+      initialize_ring $i
+    fi
   done
-  [[ $ring_missing != "0" ]] && initialize_rings
 
   for i in $RINGS ; do
     add_to_ring $i $ZONE $IP $PORT $DEVICE || exit 1
   done
-  for i in $RINGS ; do
-    rebalance_ring $i || exit 1
-  done
-  stamp=`date +%Y%M%d-%H%M%S`
-  export_dir="$WWW_DIR/$stamp"
-  mkdir $export_dir
-  echo "Copying rings to $export_dir for client consumption"
-  relation-set update_url="http://$IP/$stamp"
+
+  if [[ $(relation-get | wc -l) -lt $REPLICAS ]] ; then
+    echo "Not enough peers, will not balance rings yet."
+    exit 0
+  fi
+
+#  for i in $RINGS ; do
+#    rebalance_ring $i || exit 1
+#  done
+#  stamp=`date +%Y%M%d-%H%M%S`
+#  export_dir="$WWW_DIR/$stamp"
+#  mkdir $export_dir
+#  echo "Copying rings to $export_dir for client consumption"
+#  relation-set update_url="http://$IP/$stamp"
 }
 
+ensemble-log "swift-proxy: Firing hook $ARG0"
 case $ARG0 in
   "install") install_hook ;;
   "start"|"stop") exit 0 ;;
